[[redirects]]
  from = "/chat"
  to = "https://prime-chat.netlify.app/chat"
  status = 200
  force = true
  headers = { X-From = "Netlify" }

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"